swagger: "2.0"
info:
  version: "1.0.0"
  title: "ArgentBank Transactions API"
  description: "API permettant aux utilisateurs de gérer et de visualiser leurs transactions."

paths:
  /transactions:
    get:
      summary: "Récupérer les transactions du mois en cours groupées par compte"
      description: "Cet endpoint retourne les transactions de l'utilisateur authentifié pour le mois en cours, groupées par compte."
      parameters:
        - name: userId
          in: query
          required: true
          type: string
          description: "L'ID de l'utilisateur pour lequel les transactions doivent être récupérées."
      responses:
        '200':
          description: "Transactions récupérées avec succès"
          schema:
            type: object
            properties:
              accounts:
                type: array
                items:
                  type: object
                  properties:
                    accountId:
                      type: string
                    transactions:
                      type: array
                      items:
                        $ref: '#/definitions/Transaction'
        '401':
          description: "Non autorisé. L'utilisateur doit être authentifié."
        '500':
          description: "Erreur serveur interne."

  /transactions/{transactionId}:
    get:
      summary: "Récupérer les détails d'une transaction"
      description: "Retourne les détails d'une transaction spécifique pour l'utilisateur authentifié."
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: "L'ID de la transaction à récupérer."
      responses:
        '200':
          description: "Détails de la transaction récupérés avec succès"
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: "Transaction non trouvée."
        '401':
          description: "Non autorisé. L'utilisateur doit être authentifié."
        '500':
          description: "Erreur serveur interne."

    put:
      summary: "Modifier les informations d'une transaction"
      description: "Modifie les détails d'une transaction spécifique pour l'utilisateur authentifié."
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: "L'ID de la transaction à modifier."
        - in: body
          name: transaction
          description: "Les nouvelles informations de la transaction."
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        '200':
          description: "Transaction mise à jour avec succès."
        '400':
          description: "Requête invalide, données incorrectes."
        '404':
          description: "Transaction non trouvée."
        '401':
          description: "Non autorisé. L'utilisateur doit être authentifié."
        '500':
          description: "Erreur serveur interne."

    delete:
      summary: "Supprimer certaines informations d'une transaction"
      description: "Supprime des informations sur une transaction spécifique, sans supprimer la transaction en elle-même."
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: "L'ID de la transaction dont certaines informations doivent être supprimées."
      responses:
        '200':
          description: "Informations supprimées avec succès."
        '404':
          description: "Transaction non trouvée."
        '401':
          description: "Non autorisé. L'utilisateur doit être authentifié."
        '500':
          description: "Erreur serveur interne."

definitions:
  Transaction:
    type: object
    properties:
      transactionId:
        type: string
      accountId:
        type: string
      amount:
        type: number
        format: float
      date:
        type: string
        format: date
      description:
        type: string
      category:
        type: string
